/*------------------------------------------------------------------------------
    Copyright Butterfly Energy Systems 2014-2015, 2022.
    Distributed under the Boost Software License, Version 1.0.
    http://www.boost.org/LICENSE_1_0.txt
------------------------------------------------------------------------------*/

/**
@page ErrorsTutorial Error Handling

@tableofcontents

This page describes how error handling is done via `ErrorOr`.

ErrorOr and Exceptions
----------------------

Whenever an asynchronous wamp::Session operation fails, it will emit a
wamp::ErrorOr that contains a [`std::error_code`][error_code] instead of an
actual result.

The wamp::ErrorOr::value method would normally be used to retrieve the
underlying result of the asynchronous operation. If the `ErrorOr` instead
contains an error, `ErrorOr::value` will throw a wamp::error::Failure
exception. Since `Failure` derives from [`std::system_error`][system_error],
it contains a `std::error_code` that represents the cause of the error.

Example using error codes:

```
using namespace wamp;
AsioContext ioctx;
auto tcp = TcpConnector::create<Json>(ioctx, {"localhost", 8001});

boost::asio::spawn(ioctx, [&](boost::asio::yield_context yield)
{
    auto session = Session::create(ioctx, tcp);
    auto index = session->connect(yield);
    if (!index)
    {
        std::cerr << "Connect failed: " << index.error() << "\n";
        return;
    }

    auto info = session->join(Realm("somerealm"), yield);
    if (!info)
    {
        std::cerr << "Join failed: " << info.error() << "\n";
        return;
    }

    // etc.
});

ioctx.run();

```

Example using exceptions:

```
using namespace wamp;
AsioContext ioctx;
auto tcp = TcpConnector::create<Json>(ioctx, {"localhost", 8001});

boost::asio::spawn(ioctx, [&](boost::asio::yield_context yield)
{
    auto session = Session::create(ioctx, tcp);
    try
    {
        session->connect(yield).value(); // Note the .value()
        session->join(Realm("somerealm"), yield).value(); // Note the .value()
        // etc.
    }
    catch (const error::Failure& e)
    {
        // Print a message describing the error
        std::cerr << e.what() << "\n";

        // Obtain the std::error_code associated with the exception
        auto ec = e.code();
        if (ec == SessionErrc::noSuchRealm)
            std::cerr << "The realm doesn't exist\n";
        else
            std::cerr << "Unexpected error: " << ec << "\n";
    }
});

ioctx.run();

```

Error Codes
-----------

An error code can either belong to [`std::generic_category`][generic_category],
or to one of the error categories defined by the library in `<cppwamp/error.hpp>`:

Error category            | Values                | Used for reporting
------------------------- | ----------------------| ------------------
`wamp::SessionCategory`   | `wamp::SessionErrc`   | WAMP session errors
`wamp::ProtocolCategory`  | `wamp::ProtocolErrc`  | invalid WAMP messages
`wamp::TransportCategory` | `wamp::TransportErrc` | general transport layer errors
`wamp::RawsockCategory`   | `wamp::RawsockErrc`   | raw socket transport errors
[`std::generic_category`][generic_category] | [`std::errc`][std_errc] | OS-level socket errors


Failed Preconditions
--------------------
Note that `Session` will always throw wamp::error::Logic exceptions
whenever preconditions are not met. Preconditions for API functions are listed
in this reference documentation.

[system_error]: http://en.cppreference.com/w/cpp/error/system_error
[error_code]: http://en.cppreference.com/w/cpp/error/error_code
[generic_category]: http://en.cppreference.com/w/cpp/error/generic_category
[std_errc]: https://en.cppreference.com/w/cpp/error/errc

- - -

Next: @ref RpcTutorial

*/
